### PR TITLE
Fixed Write page

### PR DESCRIPTION
**Pull request by Nikhil7174**
Fixes issue #6

Screenshot (214)
Screenshot (215)
Screenshot (216)
Screenshot (217)

### CODE REVIEW

**Comment by Aryan-Srivastava** [comment]
1. There shouldn't be any outline when user click on text field, remove ouline, border.
2. User Should not be able to resize Tell a story section, and it should cover upto the whole page.
3. Publish button should be aligned with the Title column, it looks odd.
4. The Icon for add Image button looks odd, add some padding to it also keep it a bit distant from Title .
5. Title Should span and cover whole space under the image.
6. And using a different color for input fields in dark mode looks odd when you're not using a different color in light mode.
Your should refer to hashnode or medium write section

**Comment by Aryan-Srivastava** [comment]
You Should really move the sidebar_logo.png to public folder, It sure looks odd in components.

**Comment by Aryan-Srivastava** [comment]
Also remove `widht: max-content` at line67 in index.css from # dark .home as it'll enable horizontal scrolling on home page while in dark mode.

**Comment by Nikhil7174** [comment]
Screenshot (220)Screenshot (222)
Screenshot (224)

**Comment by Aryan-Srivastava** [comment]
Not all checks have been passed.

**Comment by Nikhil7174** [comment]
@Aryan-Srivastava Which check is still not resolved?

**Comment by Aryan-Srivastava** [comment]
When you create a new component first import it in index.js file inside component folder then export it, follow the same convention for pages as well, don't import them directly like this `import BottomBar from '../components/BottomBar.jsx'` this should be like `import { BottomBar } from '../components'`.
Have requested some minor changes and gave some examples for them as well, please go through it, it'll just take few minutes.

**Comment by Aryan-Srivastava** [comment]
Hey, @Nikhil7174 please read the above reviews for minor fixes.

**Comment by Nikhil7174** [comment]
- [x] Removed BottomBar from write page in mobile view
- [x] Removed outline from textfield
- [x] User wont be able to expand tell a story section and the texfield auto expands to fit all the text.
- [x] Publish button aligned with the title column
- [x] Added padding to Icon for add Image button and kept it a bit distant from title
- [x] Title spans whole space under the image
- [x] Removed different color of textfield in dark mode
- [x] Imported BottomBar to index.js

**Comment by Nikhil7174** [comment]
Screenshot (263)
Screenshot (265)
Screenshot (266)

**Comment by Aryan-Srivastava** [comment]
Did a Great job 👍 @Nikhil7174

**Pull request merged**
