### PR TITLE
Fixes issue #4

### PR DESCRIPTION
**Pull request by Nikhil7174**
Made the website mobile responsive

### CODE REVIEW

**Comment by Aryan-Srivastava** [comment]
Can you attach a screenshot for reference

**Comment by Nikhil7174** [comment]
Screenshot (122)
Screenshot (123)
Screenshot (124)

**Comment by Aryan-Srivastava** [comment]
Hey it look great but wouldn't it be best to put the topbar content in the bottom, home icon, about icon, contact, write and settings icon ? It'll look more mobile friendly I guess, would be great if you can take up the task.

**Comment by Nikhil7174** [comment]
@Aryan-Srivastava do you want that when the user clicks on the hamburger in the top bar they should be directed to a footer containing all the top bar content?

**Comment by Aryan-Srivastava** [comment]
no make it visible all the time, like navigation keys on bottom

**Comment by Aryan-Srivastava** [comment]
Attach screenshots

**Comment by Nikhil7174** [comment]
Screenshot (132)

**Comment by Aryan-Srivastava** [comment]
Great Work !

**Comment by Aryan-Srivastava** [comment]
#4

**Pull request merged**
