### PR TITLE
Create CODE OF CONDUCT File

### LINKED ISSUE #10: docs: Create CODE_OF_CONDUCT and CONTRIBUTING.md
To help newbies better understand about contribution and open source.

### PR DESCRIPTION
**Pull request by the-amazing-atharva**
Fixes #10 

Hey,
Created a CODE OF CONDUCT file.
Will make further updates and CONTRIBUTING File later!!

Do merge if you liked it or comment the suggestions to improve the file!!

### CODE REVIEW

**Review by Aryan-Srivastava — APPROVED** [review]
LGTM

**Comment by Aryan-Srivastava** [comment]
hey @the-amazing-atharva are you done with the contributing file, if yes do commit, and must do fetch and pull before doing commit to get changes done locally to you too.

**Comment by the-amazing-atharva** [comment]
Yeah done with the contributions !!!

**Comment by Aryan-Srivastava** [comment]
Great, Before pushing the changes keep your local branch up to date.

**Comment by the-amazing-atharva** [comment]
Done!

**Comment by the-amazing-atharva** [comment]
Closing this PR and sending another to avoid conflict as I deleted the fork

**Comment by the-amazing-atharva** [comment]
Done !!

**Comment by Aryan-Srivastava** [comment]
Umm I guess you didn't commit the CONTRIBUTING file

**Comment by the-amazing-atharva** [comment]
Will have to work on it and research bro

I am thinking that for now , you could merge this PR and then by Feb I can also make a contributing file

**Review by Aryan-Srivastava — APPROVED** [review]
LGTM

**Pull request merged**
