### PR TITLE
Update Settings.jsx

### PR DESCRIPTION
**Pull request by abhinavmalhotra01**
i put the labels in 2 sections and added tailwind classes to button

### CODE REVIEW

**Comment by Aryan-Srivastava** [comment]
Can you add some screenshot for it.

**Comment by abhinavmalhotra01** [comment]
Screenshot 2023-01-28 131517

**Comment by Aryan-Srivastava** [comment]
Looks good, It'll be great if you can add a subtle light gray bottom border for input field, It might look good and make input field more clear.

**Comment by abhinavmalhotra01** [comment]
ok sir , and on hover also gray color for border ? because currently the blue color looks odd.

**Comment by Aryan-Srivastava** [comment]
Yes something like a bg-gray-50 without hover and a bit dark for hover something like bg-gray-200 or anything that looks good.

**Comment by abhinavmalhotra01** [comment]
wo hover

**Comment by abhinavmalhotra01** [comment]
couldnt click screenshot with hover on 😅 , it is darker and has 0.5 more width than current.

**Comment by Aryan-Srivastava** [comment]
This looks good ! you can commit the changes I'll merge.

**Comment by abhinavmalhotra01** [comment]
ok sir thanks

**Review by Aryan-Srivastava — APPROVED** [review]
LGTM 👍

**Comment by Aryan-Srivastava** [comment]
Closes #8

**Pull request merged**
